name: lucky_sign
description: 今日幸运签
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2
  stomp_dart_client: ^2.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
